### ISSUE TITLE
PHP upgrade 7.4       PHP Fatal error:  Uncaught Error: Class 'Memcached' 

### ISSUE THREAD

**Issue by M4LWare666** [AlexaCRM/integration-dynamics#29]
I believe this issue could be related to #25 
WordPress version 5.6
dynamics 365 integration: 1.2.28

When I upgrade PHP versions 7.2 to 7.2 produces internal 500 error. 
Error.log below.

`Stack trace:`
`#0 /wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php(963): AlexaCRM\WordpressCRM\Cache\PhpFastCache::memcached_addserver()
#1 /wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php(1197): AlexaCRM\WordpressCRM\Cache\PhpFastCache::getMemoryName('_organization_s...')
#2 /wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php(659): AlexaCRM\WordpressCRM\Cache\PhpFastCache::memcached_get('organization_so...')
#3 /wp-content/plugins/integration-dynamics/src/Cache.php(113): AlexaCRM\WordpressCRM\Cache\PhpFastCache::get('organization_so...')
#4 /wp-content/plugins/integration-dynamics/vendor/alexacrm/php-crm-toolkit/src/SoapActions.php(81): AlexaCRM\WordpressCRM\Cache->get('organization_so. in /wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 1149`

**Comment by M4LWare666** [comment]
Resolved needed to installed `php7.4 memcache`
